blog/article/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name ="article"

urlpatterns =[
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name ="index"),
    path('about/', views.about, name ="about"),
    path('articles/',include("article.urls")),
    path('user/', include("user.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/user/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name ="user"

urlpatterns =[
    path('register/',views.register,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),
]

blog/article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.


class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE,verbose_name = "Yazar")
    title = models.CharField(max_length = 50,verbose_name = "Başlık")
    content = RichTextField(verbose_name ="İçerik")
    created_date = models.DateTimeField(auto_now_add=True, verbose_name = "Oluşturulma Tarihi")
    article_image = models.FileField(blank = True,null = True,verbose_name="Makaleye Fotoğraf Ekleyin")

    def __str__(self):
        return self.title

class Comment(models.Model):
    article =models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name = "Makale",related_name="comments")

    comment_author = models.CharField(max_length = 53, verbose_name="İsim")
    comment_content = models.CharField(max_length = 200, verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content

blog/user/models.py
from django.db import models

# Create your models here.

blog/user/forms.py
from django import forms

class RegisterForm(forms.Form):

    username = forms.CharField(max_length=50,label = "Kullanıcı Adı")
    password = forms.CharField(max_length=20,label = "Parola",widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label = "Parolayı Doğrula" ,widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")
        if password and confirm and password != confirm:
            raise forms.ValidationError("Parolalar Eşleşmiyor")
        
        values = {
            "username" : username,
            "password" : password
        }
        return values


class LoginForm(forms.Form):
    username = forms.CharField(label="Kullanıcı Adı")
    password = forms.CharField(label="Parola",widget=forms.PasswordInput)

blog/article/views.py
from django.shortcuts import render, HttpResponse,redirect,get_object_or_404,reverse
from .models import Article, Comment

# Create your views here.

def articles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()

    return render(request,"articles.html",{"articles":articles})


def index(request):

    context ={
        "numbers":[1,2,3,4,5,6]

    }
    return render(request,"index.html",context)

def about(request):
    return render(request,"about.html")

blog/user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages


# Create your views here.

def register(request):

    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        newUser = User(username =username)
        newUser.set_password(password)

        newUser.save()
        login(request,newUser)
        messages.info(request,"Başarıyla Kayıt Oldunuz...")

        return redirect("index")
    context = {
            "form" : form
        }
    return render(request,"register.html",context)

def loginUser(request):

    form = LoginForm(request.POST or None)
    context = {
        "form":form
    }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username,password = password)

        if user is None:
            messages.info(request,"Kullanıcı Adı veya Parola Hatalı")
            return render(request,"login.html",context)

        messages.success(request,"Başarıyla Giriş Yaptınız")
        login(request,user)
        return redirect("index")
    return render(request,"login.html",context)


def logoutUser(request):
    logout(request)
    messages.success(request,"Başarıyla Çıkış Yaptınız.")
    return render(request,"index.html")

blog/templates/about.html
{% extends "layout.html" %}

{% block body %}

    <h3>Hakkımızda</h3>
    <hr>

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsam explicabo quo aliquid officiis velit, numquam aspernatur dignissimos eos et a quisquam quibusdam enim? Earum assumenda ratione iure itaque dolores debitis?</p>

{% endblock body %}

blog/templates/includes/navbar.html
<script>

        function darkMode(renk) {
            document.body.style.background = renk;
            var h1Elements = document.getElementsByTagName("h1");
            for (var i = 0; i < h1Elements.length; i++) {
                h1Elements[i].style.color = "#ffffff";
            }
        }

        function lightMode(renk) {
            document.body.style.background = renk;
            var h1Elements = document.getElementsByTagName("h1");
            for (var i = 0; i < h1Elements.length; i++) {
                h1Elements[i].style.color = "#000000";
            }
        }
    </script>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'index' %}">Emirhan Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'about' %}">Hakkımızda</a>
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
              <a href="#" type="button" onclick="darkMode('Black')" class="nav-link">Dark Mode</a></li>

          <li class="nav-item active">
              <a href="#" type="button" onclick="lightMode('White')" class="nav-link">Light Mode</a></li>

          {% if request.user.is_authenticated %}

          <li class="nav-item active">
              <a class="nav-link" href="{% url 'user:logout' %}">Çıkış Yap</a></li>


          {% else %}
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'user:login' %}">Giriş Yap</a></li>
        

          {% endif %}
          <li class="nav-item active">
              <a class="nav-link" href="{% url 'user:register' %}">Kayıt Ol</a></li>
      
       
            
       </ul>
          
        </div>
      </nav>

blog/templates/includes/posttemplate.html
<div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">
    
          <!-- Title -->
          <h1 class="mt-4">Post Title</h1>
    
          <!-- Author -->
          <p class="lead">
            by
            <a href="#">Start Bootstrap</a>
          </p>
    
          <hr>
    
          <!-- Date/Time -->
          <p>Posted on January 1, 2018 at 12:00 PM</p>
    
          <hr>
    
          <!-- Preview Image -->
          <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">
    
          <hr>
    
          <!-- Post Content -->
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>
    
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>
    
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>
    
          <blockquote class="blockquote">
            <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
            <footer class="blockquote-footer">Someone famous in
              <cite title="Source Title">Source Title</cite>
            </footer>
          </blockquote>
    
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>
    
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>
    
          <hr>
    
          <!-- Comments Form -->
          <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
              <form>
                <div class="form-group">
                  <textarea class="form-control" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
          </div>
    
          <!-- Single Comment -->
          <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
            </div>
          </div>
    
          <!-- Comment with nested comments -->
          <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0">Commenter Name</h5>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
    
              <div class="media mt-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                  <h5 class="mt-0">Commenter Name</h5>
                  Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
              </div>
    
              <div class="media mt-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                  <h5 class="mt-0">Commenter Name</h5>
                  Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                </div>
              </div>
    
            </div>
          </div>
    
        </div>
    
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">
    
          <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div>
    
          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">Web Design</a>
                    </li>
                    <li>
                      <a href="#">HTML</a>
                    </li>
                    <li>
                      <a href="#">Freebies</a>
                    </li>
                  </ul>
                </div>
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">JavaScript</a>
                    </li>
                    <li>
                      <a href="#">CSS</a>
                    </li>
                    <li>
                      <a href="#">Tutorials</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
    
          <!-- Side Widget -->
          <div class="card my-4">
            <h5 class="card-header">Side Widget</h5>
            <div class="card-body">
              You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
            </div>
          </div>
    
        </div>
    
      </div>

blog/templates/index.html
{% extends "layout.html" %}

{% block body %}

{% csrf_token %}

<div class ="jumbotron text-center">
        <h3>Bloğa Hoş Geldiniz</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis unde perspiciatis, nisi deserunt ullam minima fugit quia et nemo repudiandae odio accusamus consequuntur aliquid architecto cum provident voluptate ea consequatur.</p>

</div>

<p>
        {% if request.user.is_authenticated %}
                Giriş Yapılmış, {{request.user.username}}
        {% else %}
                Giriş Yapılmamış.
        {% endif %}


</p>

{% endblock body %}

blog/templates/layout.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <title>Blog</title>
</head>
<body>  
        {% include "includes/navbar.html" %}

        

        <div style = "margin-top : 100px; margin-bottom:100px;" class = "container">
                
            {% if messages %}
                
                    {% for message in messages %}
                    {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                    {% endif %}


                    {% endfor %}
                
                {% endif %}
            {% block body %}
            
            {% endblock body %}

        </div>
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js'%}"></script>
        <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>

      
    </body>
</html>

blog/templates/login.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş Yap</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Giriş Yap</button>
        </form>
    </div>
  </div>

{% endblock body %}

blog/templates/register.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt Ol</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Giriş Yap</button>
        </form>
    </div>
  </div>

{% endblock body %}